

# Scope of the SWIM package



## Stressing a model {#Rfunctions}


We define a **model** to consist of a random vector $\boldsymbol{X} = (X_1, \ldots, X_n)$, the *input factors*, a function $g \colon \mathbb{R}^n \to \mathbb{R}$, called the *aggregation function*, which gives, when applied to the input factors $\boldsymbol{X}$, the one-dimensional random *output* of interest $Y = g(\boldsymbol{X})$. Starting from a **baseline probability**, $P$, a probability measure describing the current beliefs regarding (or software implementation of) the model, we are interested in **stressed models** that fulfil probabilistic constraints and have minimal Kullback-Leibler divergence. Specifically, a **stressed probability** $Q$ is the solution to 
\begin{equation} 
\min_{ Q \in \mathcal{P}} D_\text{KL}(Q \| P), \quad
\text{s.t. probabilistic constraints of the model under }Q \text{ hold},
(\#eq:optimisation)
\end{equation}
where the Kullback-Leibler divergence is given by $D_\text{KL}(Q \| P)  = \int \frac{dQ}{dP} \log \big(\frac{dQ}{dP} \big)\mathrm{d}P$, if $Q$ is absolutely continuous with respect to $P$. The probabilistic constraints in \@ref(eq:optimisation) can be with respect to (one of) the inputs or the output. For simpilcity of notation, we henceforth stress the output of a model, however, the SWIM package allows to choose the input or output variable on which the stress is applied. 







### Stressing disjoint probability intervals 

An example of optimisation \@ref(eq:optimisation), studied by @Csiszar1975, @Cambou2017, has disjoint probability intervals as constraints. Specifically, let $B_1, \ldots, B_I$ be disjoint sets with $P(Y \in B_i) >0$, for all $i = 1, \ldots, I$, and $\alpha_1, \ldots, \alpha_I > 0$ such that $\alpha_1 + \ldots  + \alpha_I < 1$. Then the solution to 
\begin{equation} 
\min_{ Q \in \mathcal{P}} D_\text{KL}(Q \| P), \quad
\text{s.t. } Q(Y \in B_i) = \alpha_i, ~i = 1, \ldots, I.
\end{equation}
is discribed by the change-of-measure (Radon-Nikodym derivative) from $P$ to $Q$
\begin{equation} 
w  = \sum_{i = 0}^I \frac{\alpha_i}{P(Y \in B_i)}1_{ \{Y \in B_i
\}},
\end{equation}
where $\alpha_0 = 1 - \alpha_1 + \ldots + \alpha_I$ and $B_0 = \Big( \bigcup_{i = 1}^I B_i \Big)^c$.    

From a risk management point of view, a stress on a risk measure such as the Value-at-Risk ($\text{VaR}$) and the Expected Shortfall ($\text{ES}$) is of interest. The $\text{VaR}$ at level $0 < \alpha < 1$ of a random variable $Z$ with distrbution $F$, is defined as the $\alpha-$quantile of $F$, that is $\text{VaR}_\alpha(Z) = F^{-1}(\alpha)$. The $\text{ES}$ at level $0 < \alpha < 1$ of a random variable $Z$ is given by $\text{ES}_\alpha(Z) = \int_0^1 \text{VaR}_u(Z) \mathrm{d}u$.


### Stressing moments 

The functions `stress_mean()`, `stress_mean_sd()` and `stress_moment()` can be applied to multiple input / output variables and are the only `stress` function which weight function is not in analytical form and thus obtained via numerical optimisation using the [nleqslv](https://CRAN.R-project.org/package=nleqslv) package. 




### Stressing risk measures



### Implemented stresses
The SWIM package provides sensitivity analysis tools for stressing model
components (random variables). 

| R function             | Stress                                |
| ---------------------- | -----------------------------         |
| `stress()`             | a wrapper for the `stress_` functions |
| `stress_VaR()`         | VaR risk measure, a quantile          |
| `stress_VaR_ES()`      | VaR and ES risk measures              |
| `stress_mean()`        | means                                 |
| `stress_mean_sd()`     | means and standard deviations         |
| `stress_moment()`      | moments, functions of moments         |
| `stress_prob()`        | probabilities of intervals            |
| `stress_user()`        | user defined scenario weights         |




## Visual tools











