---
title: Scenario Weights for Importance Measurement (**SWIM**) -- an **R** package
  for sensitivity analysis
author: Silvana M. Pesenti^[Correspondence to Silvana Pesenti, Department of Statistical
  Sciences, University of Toronto, Canada. silvana.pesenti@utoronto.ca] ^2^, Alberto
  Bettini^3^, Pietro Millossovich^4,5^, Andreas Tsanakas^5^
date: "| ^2^University of Toronto, ^3^Assicurazioni Generali S.p.A, ^4^DEAMS, University
  of Trieste, ^5^Cass Business School, City, University of London\n|\n| 05. March
  2021 \n"
bibliography: bibliography.bib
documentclass: article
github-repo: spesenti/SWIMvignette
link-citations: yes
site: bookdown::bookdown_site
biblio-style: apalike
abstract: The **SWIM** package implements a flexible sensitivity analysis framework,
  based primarily on results and tools developed by @Pesenti2019. **SWIM** provides
  a stressed version of a stochastic model, subject to model components (random variables)
  fulfilling given probabilistic constraints (stresses). Possible stresses can be
  applied on moments, probabilities of given events, and risk measures such as Value-at-Risk
  and Expected Shortfall. **SWIM** operates upon a single set of simulated scenarios
  from a stochastic model, returning scenario weights, which encode the required stress
  and allow monitoring the impact of the stress on all model components. The scenario
  weights are calculated to minimise the relative entropy with respect to the baseline
  model, subject to the stress applied. As well as calculating scenario weights, the
  package provides tools for the analysis of stressed models, including plotting facilities
  and evaluation of sensitivity measures. **SWIM** does not require additional evaluations
  of the simulation model or explicit knowledge of its underlying statistical and
  functional relations; hence it is suitable for the analysis of black box models.
  The capabilities of **SWIM** are demonstrated through a case study of a credit portfolio
  model.
---

``` {r, setup, echo=FALSE, cache=FALSE}
options(digits = 2) # auto round to 2 decimals when printed
```


**Keywords**: Sensitivity analysis; risk measures; stress testing; sensitivity measures, Kullback-Leibler divergence

# Introduction

## Background and contribution

Complex quantitative models are used extensively in actuarial and financial risk management applications, as well as in wider fields such as environmental risk modelling [@Tsanakas2016b; @Borgonovo2016; @Pesenti2019]. The complexity of such models (high dimensionality of inputs; non-linear relationships)  motivates the performance of sensitivity analyses, with the aim of providing insight into the ways that model inputs interact and impact upon the model output. 


When model inputs are subject to uncertainty, *global* sensitivity methods are often used, considering the full space of (randomly generated) multivariate scenarios, which represent possible configurations of the model input vector. The particular task of ranking the importance of different model inputs leads to the use of sensitivity measures, which assign a score to each model input. A rich literature on global sensitivity analysis exists, with variance decomposition methods being particularly prominent; see @Saltelli2008 and @Borgonovo2016 for wide-ranging reviews.  The **R** package **sensitivity** [@Rsensitivity] implements a wide range of sensitivity analysis approaches and measures. 




We introduce an alternative approach to sensitivity analysis called *Scenario Weights for Importance Measurement* (**SWIM**) and present the **R** package implementing it [@PesentiR]. This approach was developed with actuarial risk models in mind, particularly those used for risk management and economic capital calculations. The aim of this paper is to provide an accessible introduction to the concepts underlying **SWIM** and a vignette demonstrating how the package is used. **SWIM** quantifies how distorting a particular model component (which could be a model input, output, or an intermediate quantity) impacts all other model components. The **SWIM** approach can be summarised as follows:

    
1. The starting point is a table of simulated scenarios, each column containing realisations of a different model component. This table forms the *baseline model* as well as the dataset on which the **SWIM** bases its calculations.     

2. A *stress* is defined as a particular modification of a model component (or group of components). This could relate to a change in moments, probabilities of events of interest, or risk measures, such as Value-at-Risk or Expected Shortfall (e.g. @Mcneil2015B). Furthermore, there is the facility for users to design their own stresses, involving potentially more than one model component. 

3. **SWIM** calculates a set of *scenario weights*, acting upon the simulated scenarios and thus modifying the relative probabilities of scenarios occurring. Scenario weights are derived such that the defined stress on model components is fulfilled, while keeping the distortion to the baseline model to a minimum, as quantified by the Kullback-Leibler divergence (relative entropy). Alternatively, users are able to import their own set of weights, generated by a method of their choice.

4. Given the calculated scenario weights, the impact of the stress on the distributions of all model components is worked out and sensitivity measures, useful for ranking model components, are evaluated. 

A key benefit of **SWIM** are that it provides a sensitivity analysis framework that is economical both computationally and in terms of the information needed to perform the analysis. Specifically, sensitivity analysis is performed using only one set of simulated scenarios. No further simulations are needed, thus eliminating the need for repeated evaluation of the model, which could be numerically expensive. Furthermore, the user of **SWIM** needs to know neither the explicit form of the joint distribution of model components nor the exact form of functional relations between them. Hence, **SWIM** is appropriate for the analysis of *black box* models, thus having a wide scope of applications. Specifically, SWIM is well suited to simulation models used in insurance risk management, which are characterised by high dimensions, complex interactions between risk factors, and high computational cost of re-simulating under different assumptions.

While there is an extensive literature on sensitivity analysis and there exist multitudes of sensitivity measures, our proposed sensitivity analysis framework differs in that it is model independent and can be applied numerically efficient since it does not require potentially expensive re-evaluation of the model's output. Moreover, while variance-based and moment-independent sensitivity measures are widely used in risk analysis [@borgonovo2016common], in risk management applications model components are often summaries using risk measure [@Mcneil2015B]. 

The proposed sensitivity analysis framework implemented in **SWIM** is based on theoretical results derived in @Pesenti2019. While these results hold in generality, the **SWIM** packages fundamentally hinges on the fact that it works on a set of Monte Carlo simulations. Thus, the quality of the sensitivity analysis conducted using **SWIM** is intimately connected with the quality of the dataset. The aim of the **SWIM** package is to make the novel sensitivity analysis framework easily and freely accessible, however, as with any sensitivity analysis tool, it does not provide guidance on the interpretation of the results nor the plausibility of a stressed model. Nevertheless, the authors believe that especially the visual tools, e.g. plotting of histograms, will provide users with insight regarding the relationship between different model components and structure. 

The **SWIM** approach is largely based on @Pesenti2019 and uses theoretical results on risk measures and sensitivity measures developed in that paper. An early sensitivity analysis approach based on scenario weighting was proposed by @Beckman1987. The Kullback-Leibler divergence has been used extensively in the financial risk management literature -- papers that are conceptually close to **SWIM** include @Weber2007; @Breuer2013; and @Cambou2017. Some foundational results related to the minimisation of the Kullback-Leibler divergence are provided in @Csiszar1975dAP.

## Installation

The **SWIM** package can be installed from [CRAN](https://CRAN.R-project.org/package=SWIM) or through [GitHub](https://github.com/spesenti/SWIM): 

``` r}
# directly from CRAN
install.packages("SWIM")
# and the development version from GitHub 
devtools::install_github("spesenti/SWIM")
```

## Structure of the paper

Section \@ref(Sec:Intro) provides an introduction to **SWIM**, illustrating key concepts and basic functionalities of the package on a simple example. Section 
\@ref(Sec:Scope) contains technical background on the optimisations that underlay the **SWIM** package implementation. Furthermore, Section \@ref(Sec:Scope) includes a brief reference guide, providing an overview of implemented **R** functions, objects, and graphical/analysis tools.  Finally, a detailed case study of a credit risk portfolio is presented in Section \@ref(Sec:CreditModel). Through this case study, advanced capabilities of **SWIM** for sensitivity analysis are demonstrated, including more complex user-designed stresses.


